import { defineConfig } from "eslint/config";
import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

export default defineConfig([
  {
    ignores: [".next/**", "next-env.d.ts"],
  },
  ...coreWebVitals,
  ...typescript,
  {
    // shadcn/ui primitives are vendored upstream code, regenerated by the CLI.
    // Their embla/toast patterns trip the React compiler rules; keep them
    // visible as warnings instead of rewriting code we don't maintain.
    files: ["src/components/ui/**"],
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
    },
  },
]);
