import { defineConfig } from "eslint/config";
import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

export default defineConfig([
  {
    ignores: [".next/**", "next-env.d.ts"],
  },
  ...coreWebVitals,
  ...typescript,
  {
    // shadcn/ui primitives are vendored upstream code, regenerated by the CLI.
    // Their embla/toast patterns trip these rules and we will not rewrite code
    // we don't maintain, so the rules are off rather than permanently noisy.
    files: ["src/components/ui/**"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
]);
